language: python

sudo: false

env:
  # Default values for common packages, override as needed
  global:
    - COVERAGE=true

matrix:
  fast_finish: true
  include:
  - python: 2.7
    env:
    - PYTHON=2.7
    - PANDAS=0.15
  - python: 2.7
    env:
    - PYTHON=2.7
    - PANDAS=0.17
  - python: 2.7
    env:
    - PYTHON=3.4
    - PANDAS=0.16
  - python: 2.7
    env:
    - PYTHON=3.5
  - python: 2.7
    env:
    - PYTHON=3.6

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes --quiet conda
  # Build package list to avoid empty package=versions; only needed for versioned packages
  - PKGS="python=${PYTHON}"
  - PKGS="${PKGS} pandas"; if [ ${PANDAS} ]; then PKGS="${PKGS}=${PANDAS}"; fi

# Install packages
install:
  - conda create --yes --quiet -n pandas-stash-test ${PKGS} ${OPTIONAL} pytables
  - source activate pandas-stash-test
  - pip install flake8 coverage pytest coveralls pytest-cov codecov pytest-xdist
  - python setup.py build

script:
  - SRCDIR=$PWD
  - python setup.py install
  - python -c 'import pandas as pd; pd.show_versions();'
  - py.test -n 2 -s --cov=pandas_stash --pyargs pandas_stash
  - flake8 pandas_stash --exclude=*test*,*\doc\*,setup.py

after_success:
  - if [ ${COVERAGE} = true ]; then coveralls --rcfile=${SRCDIR}/.travis_coveragerc; fi
  - if [ ${COVERAGE} = true ]; then codecov; fi

